name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '10.24.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pre-commit
        pre-commit install -f --install-hooks
        yarn global add @vue/cli@v4.5.15
        yarn install

    - name: Lint
      run: pre-commit run -a
